# Generated by Django 4.2.5 on 2023-09-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("file_sharing_app", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="file",
            name="title",
            field=models.CharField(default="File_Name", max_length=255),
        )
    ]
